export const STATE_BUSY = "STATE_BUSY";
export const STATE_READY = "STATE_READY";
export const STATE_ERROR = "STATE_ERROR";

export const AUTH_LOG_IN = "AUTH_LOG_IN";
export const AUTH_LOG_OUT = "AUTH_LOG_OUT";
export const AUTH_BAD_CREDENTIALS = "AUTH_BAD_CREDENTIALS";
export const AUTH_BAD_CREDENTIALS_CLEAR = "AUTH_BAD_CREDENTIALS_CLEAR";

export const AUTH_STATE_LOAD = "AUTH_STATE_LOAD";
export const AUTH_STATE_SAVE = "AUTH_STATE_SAVE";
export const AUTH_STATE_CLEAR = "AUTH_STATE_CLEAR";

export const GREETING_MESSAGE_RECEIVED = "GREETING_MESSAGE_RECEIVED";

export const MESSAGE_RECEIVED = "MESSAGE_RECEIVED";

export const CONNECTION_IN_PROGRESS = "CONNECTION_IN_PROGRESS";
export const CONNECTION_ESTABLISHED = "CONNECTION_ESTABLISHED";
export const CONNECTION_LOST = "CONNECTION_LOST";
