app:
  name: app
  description: "websocket-react"
  version: "0.0.1"

api:
  version: v1
  prefix: /api/${api.version}

ws:
  version: v1
  prefix: /ws/${ws.version}

authentication:
  key: "d3b6681900dd39068483c3a0decad73fbe42acb363fb55babb87a74b22d6aac5"
  access-token-validity-seconds: 3600
  refresh-token-validity-seconds: 2592000

spring:
  main.banner-mode: "off"
  application.name: ${app.name}
  output.ansi.enabled: never

server:
  port: ${port:8081}
  use-forward-headers: true
  compression:
    enabled: true
    min-response-size: 8192
    mime-types:
      - application/json
      - text/html
      - text/css
      - application/javascript

logging:
  pattern:
    level: "%clr(%-5p)"
    console: "%date{yyyy.MM.dd HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN} %clr([%thread]){magenta} %clr(%logger{-1}){cyan}->%clr(%method){blue}: %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
  level:
    root: INFO
